import {adaptiveRefreshDelay, POST_ACTION_REFRESH_MS, STATUS_CHECK_MS, shouldRefresh} from '/refresh-scheduler.mjs';
import {chooseTargetFps, measureDisplayHz, playRealtimeStream, playMjpegStream} from '/stream-client.mjs';
import {classifyH264Failure, nextH264RetryDelay, retryDelayLabel} from '/stream-recovery.mjs';

const $=id=>document.getElementById(id), token=location.hash.slice(1);history.replaceState(null,'',location.pathname);
let connected=false,realtimeAvailable=false,mjpegAvailable=false,deviceRefreshHz=null,aiControlActive=false,startPoint=null,startClientPoint=null,pointerDownAt=0,pointerDragging=false,previewPromise=null,previewController=null,refreshTimer=null,lastActionAt=0,lastStatusAt=0,currentObjectURL='',exclusiveBusy=false,latestOperation=0;
let streamController=null,probeController=null,streamRunning=false,streamAttempt=0,targetFps=60,displayHz=60,streamFallbackReason='',activeStreamMode='',activeVideoId='video',directTouchAvailable=false,directTouchFailed=false,gestureDirectTouch=false,touchChain=Promise.resolve(),pendingTouchMove=null,touchMovePump=false,touchHealthTimer=null,touchModeState='waiting';
let h264RetryTimer=null,h264RetryFailures=0,lastH264Failure=null,previewSizeInitialized=false,lastStreamFeedbackAt=0;
let recordingState={phase:'idle',elapsedSeconds:0,maxDurationSeconds:175,items:[]},recordingBusy=false,recordingUiTimer=null,recordingPollTimer=null,lastRecordingFile='';
let devicesState={devices:[],rememberedRef:null,selectedRef:null,autoConnect:false},devicePollTimer=null,deviceRefreshPromise=null,connectionBusy=false,connectingRef=null,connectCancelled=false,autoConnectAttemptedRef=null,currentDeviceRef=null,autoConnectSuppressed=false;
let diagnosticTimer=null,diagnosticBusy=false,lastDiagnosticSnapshot=null;
let aiIntegrationState=null,aiIntegrationBusy=false;
const PREVIEW_SIZES=Object.freeze({small:320,medium:400,large:480}),PREVIEW_SIZE_LABELS=Object.freeze({small:'小',medium:'中',large:'大'});
function normalizePreviewSize(value){return Object.prototype.hasOwnProperty.call(PREVIEW_SIZES,value)?value:'medium';}
function applyPreviewSize(value){const size=normalizePreviewSize(value),wrap=document.querySelector('.phone-wrap');if(wrap)wrap.dataset.displaySize=size;document.querySelectorAll('[data-preview-size]').forEach(button=>{const active=button.dataset.previewSize===size;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});return size;}

async function api(route,body,options={}){
 const timeout=options.timeout??15000, controller=new AbortController(), timer=setTimeout(()=>controller.abort('timeout'),timeout), onAbort=()=>controller.abort('cancelled');
 if(options.signal)options.signal.addEventListener('abort',onAbort,{once:true});
 try{
  const response=await fetch('/api/'+route,{method:body===undefined?'GET':'POST',headers:{'X-AndroidLink-Token':token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});
  const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'操作失败');return data;
 }catch(e){if(controller.signal.aborted&&!options.signal?.aborted)throw new Error('操作超时，请重试。');throw e;}finally{clearTimeout(timer);if(options.signal)options.signal.removeEventListener('abort',onAbort);}
}
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function diagnosticClock(value){const date=new Date(value);return Number.isNaN(date.getTime())?'--:--:--':date.toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'});}
function diagnosticValue(id,item){const el=$(id);if(!el)return;el.textContent=item?.value||'待检查';el.className='tech diagnostic-value '+(item?.kind||'idle');if(item?.time)el.title=new Date(item.time).toLocaleString();else el.removeAttribute('title');}
function renderDiagnostics(data){lastDiagnosticSnapshot=data||lastDiagnosticSnapshot;if(!data)return;diagnosticValue('diagUsb',data.summary?.usbAdb);diagnosticValue('diagSession',data.summary?.session);diagnosticValue('diagRealtime',data.summary?.realtime);const recent=data.summary?.recentEvent||{};diagnosticValue('diagRecent',{...recent,value:recent.value?`${recent.value}${recent.time?' · '+diagnosticClock(recent.time):''}`:'等待事件'});const list=$('diagnosticEvents');if(!list)return;list.replaceChildren();const events=Array.isArray(data.events)?data.events:[];if(!events.length){const empty=document.createElement('div');empty.className='diagnostic-event empty';empty.textContent='暂无诊断事件';list.append(empty);return;}for(const event of events.slice(0,8)){const row=document.createElement('div');row.className='diagnostic-event'+(event.level==='error'?' error':'');const time=document.createElement('span');time.className='time';time.textContent=diagnosticClock(event.time);const code=document.createElement('span');code.className='code';code.textContent=event.code+(event.message&&event.message!==event.code?' · '+event.message:'');row.append(time,code);list.append(row);}}
async function refreshDiagnostics(){if(diagnosticBusy||document.hidden||!$('advancedChecks')?.open)return;diagnosticBusy=true;try{renderDiagnostics(await api('diagnostics',undefined,{timeout:5000}));}catch(error){diagnosticValue('diagRecent',{value:'监测失败',kind:'error'});const out=$('diagnosticExport');if(out){out.textContent=error.message;out.classList.add('error');}}finally{diagnosticBusy=false;}}
function stopDiagnosticPolling(){if(diagnosticTimer){clearTimeout(diagnosticTimer);diagnosticTimer=null;}}
function scheduleDiagnosticPolling(delay=0){stopDiagnosticPolling();if(document.hidden||!$('advancedChecks')?.open)return;diagnosticTimer=setTimeout(async()=>{diagnosticTimer=null;await refreshDiagnostics();scheduleDiagnosticPolling(2000);},Math.max(0,delay));}
function showMode(text,kind=''){$('streamMode').textContent=text;$('streamMode').className='tech '+kind;}
function aiIntegrationMessage(message,error=false){const el=$('aiIntegrationStatus');if(!el)return;el.textContent=message;el.classList.toggle('error',Boolean(error));el.classList.toggle('ok',!error&&/正常|已接入|已复制|已移除/.test(message));}
async function copyText(text){const value=String(text||'');if(!value)throw new Error('当前没有可复制的 MCP 配置。');if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(value);return;}catch{}}const area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const ok=document.execCommand?.('copy');area.remove();if(!ok)throw new Error('浏览器未允许复制，请手动复制开发者资料中的 MCP 配置。');}
function aiClientStateText(client){if(client.configured)return client.managed?'已接入':'已配置';if(client.detected)return client.oneClick?'已检测':'已检测 · 手动接入';return'未检测到';}
function renderAiIntegrations(data){aiIntegrationState=data||aiIntegrationState;const list=$('aiClientList');if(!list||!aiIntegrationState)return;list.replaceChildren();for(const client of aiIntegrationState.clients||[]){const row=document.createElement('div');row.className='ai-client-row';const info=document.createElement('div'),title=document.createElement('div'),name=document.createElement('strong'),state=document.createElement('span'),detail=document.createElement('small'),button=document.createElement('button');title.className='ai-client-title';name.textContent=client.name;state.className='ai-client-state tech '+(client.configured?'connected':client.detected?'detected':'missing');state.textContent=aiClientStateText(client);title.append(name,state);detail.textContent=client.detail||'';info.append(title,detail);button.className='compact';if(client.configured&&client.managed){button.textContent='移除接入';button.classList.add('danger-subtle');button.onclick=()=>changeAiIntegration(client.id,'remove');}else if(client.configured){button.textContent='已配置';button.disabled=true;}else if(client.detected&&client.oneClick){button.textContent='一键接入';button.classList.add('primary');button.onclick=()=>changeAiIntegration(client.id,'connect');}else{button.textContent=client.id==='codex'?'复制 TOML':'复制 JSON';button.onclick=async()=>{try{await copyText(client.id==='codex'?aiIntegrationState.snippets?.toml:aiIntegrationState.snippets?.json);aiIntegrationMessage(`已复制 ${client.name} 可用的 MCP 配置`);}catch(error){aiIntegrationMessage(error.message,true);}};}button.disabled=button.disabled||aiIntegrationBusy;row.append(info,button);list.append(row);}if(!(aiIntegrationState.clients||[]).some(item=>item.detected))aiIntegrationMessage('没有识别到已适配 AI；仍可复制 MCP 配置手动接入。');else aiIntegrationMessage('检测完成。自动接入只会修改明确支持且可安全合并的本机配置。');}
async function refreshAiIntegrations(){if(aiIntegrationBusy)return;try{renderAiIntegrations(await api('ai-integrations',undefined,{timeout:5000}));}catch(error){aiIntegrationMessage('AI 接入检测失败：'+error.message,true);}}
async function changeAiIntegration(client,action){if(aiIntegrationBusy)return;aiIntegrationBusy=true;renderAiIntegrations(aiIntegrationState);aiIntegrationMessage(action==='connect'?'正在写入 MCP 接入配置…':'正在移除由助手管理的 MCP 配置…');try{const result=await api(action==='connect'?'ai-connect':'ai-remove',{client},{timeout:8000});renderAiIntegrations(result.integrations||await api('ai-integrations'));aiIntegrationMessage((action==='connect'?'已接入':'已移除')+(result.restartHint?' · '+result.restartHint:''));}catch(error){aiIntegrationMessage(error.message,true);}finally{aiIntegrationBusy=false;renderAiIntegrations(aiIntegrationState);}}
function showH264Health(text='',kind='',detail=''){const el=$('h264Health');el.hidden=!text;el.textContent=text;el.className='stream-health tech '+kind;el.title=detail||'';}
function showTouchMode(mode='waiting',detail=''){touchModeState=mode;const el=$('touchMode');if(!el)return;if(mode==='scrcpy-video'){el.textContent='操控：scrcpy 实时跟手 · 视频直连';el.className='touch-mode live';}else if(mode==='scrcpy-control-only'){el.textContent='操控：scrcpy 实时跟手 · 独立触控';el.className='touch-mode live';}else if(mode==='connecting'){el.textContent='操控：实时跟手通道连接中…';el.className='touch-mode connecting';}else if(mode==='appium'){el.textContent='操控：Appium 兼容模式 · 松手后执行';el.className='touch-mode fallback';}else{el.textContent='操控：等待实时画面';el.className='touch-mode waiting';}el.title=detail||'';}
function syncTouchState(s){const tc=s?.touchControl||{},mode=tc.mode||((s?.directTouchAvailable)?'scrcpy-control-only':'appium');directTouchAvailable=Boolean(s?.directTouchAvailable||tc.realtime);showTouchMode(mode,tc.lastError||'');}
function syncAiControl(value){
 const lease=value||{active:false};aiControlActive=Boolean(lease.active);const card=$('aiControlCard'),text=$('aiControlText');
 if(card){card.hidden=!aiControlActive;if(text)text.textContent=aiControlActive?`${lease.owner||'AI'} 正在控制手机${lease.expiresAt?' · 租约自动到期':''}`:'AI 未占用控制';}
 syncControlAvailability();
 for(const surface of [$('screen'),$('video'),$('videoProbe')]){surface.classList.toggle('ai-locked-surface',aiControlActive);}
}
function syncControlAvailability(){
 const needsDevice=['back','home','recent','notifications','quickSettings','collapsePanel','refresh','save','record','input','reconnect','disconnect','source'];
 for(const id of needsDevice){const el=$(id);if(!el)continue;el.disabled=exclusiveBusy||connectionBusy||aiControlActive||!connected||(id==='record'&&recordingBusy);}
 document.querySelectorAll('[data-direction]').forEach(el=>{el.disabled=exclusiveBusy||connectionBusy||aiControlActive||!connected;});
 const textarea=$('text');if(textarea)textarea.disabled=exclusiveBusy||connectionBusy||aiControlActive||!connected;
 const inspector=$('inspector');if(inspector){inspector.style.pointerEvents=connected?'':'none';inspector.setAttribute('aria-disabled',String(!connected));}
}
function stopTouchHealthPolling(){if(touchHealthTimer){clearTimeout(touchHealthTimer);touchHealthTimer=null;}}
function scheduleTouchHealthPolling(delay=900){stopTouchHealthPolling();if(!connected||document.hidden||!streamRunning)return;touchHealthTimer=setTimeout(async()=>{touchHealthTimer=null;try{const s=await api('status',undefined,{timeout:3500});lastStatusAt=Date.now();syncTouchState(s);}catch{}scheduleTouchHealthPolling(1100);},delay);}
function reportVideoSize(event){if(!event||event.state!=='resize'||!event.width||!event.height)return;api('video-size',{width:event.width,height:event.height},{timeout:2500}).catch(()=>{});}
function reportStreamFeedback(stats){const now=Date.now();if(!stats||now-lastStreamFeedbackAt<5000)return;lastStreamFeedbackAt=now;api('stream-feedback',{mode:stats.mode,actualFps:stats.fps,targetFps:stats.targetFps},{timeout:2500}).catch(()=>{});}
function revokeFallback(){if(currentObjectURL){URL.revokeObjectURL(currentObjectURL);currentObjectURL='';}}
function hideSurfaces(){revokeFallback();$('screen').removeAttribute('src');$('screen').style.display='none';$('video').style.display='none';$('videoProbe').style.display='none';$('empty').style.display='block';}
function showVideo(id='video'){revokeFallback();activeVideoId=id;$('screen').style.display='none';$('video').style.display=id==='video'?'block':'none';$('videoProbe').style.display=id==='videoProbe'?'block':'none';$('empty').style.display='none';}
function showFallback(){$('video').style.display='none';$('videoProbe').style.display='none';$('screen').style.display='block';$('empty').style.display='none';}
async function updateState(){const s=await api('status',undefined,{timeout:5000});lastStatusAt=Date.now();connected=Boolean(s.connected);currentDeviceRef=s.currentDeviceRef||null;realtimeAvailable=Boolean(s.realtimeAvailable);mjpegAvailable=Boolean(s.mjpegAvailable);deviceRefreshHz=Number.isFinite(Number(s.deviceRefreshHz))?Number(s.deviceRefreshHz):null;applyRecordingState(s.recording);syncTouchState(s);syncAiControl(s.aiControl);if(!previewSizeInitialized){applyPreviewSize(s.previewSize);previewSizeInitialized=true;}if(s.h264Diagnostic?.lastFailure&&!lastH264Failure)lastH264Failure=classifyH264Failure(s.h264Diagnostic);if(s.inspectorURL)$('inspector').href=s.inspectorURL;else $('inspector').removeAttribute('href');$('version').textContent='v'+s.version;$('devicePanel').hidden=connected;$('connectedPreview').hidden=!connected;$('dot').classList.toggle('connected',connected);$('dot').classList.toggle('connecting',connectionBusy);$('dot').classList.remove('error');$('connection').textContent=connectionBusy?'连接中':connected?'已连接':'未连接';$('device').textContent=connected?((s.model||'Android')+(s.os?' · Android '+s.os:'')+(deviceRefreshHz?` · ${Math.round(deviceRefreshHz)} Hz`:'')):'Android 手机';$('reconnect').textContent='重新连接';if(!connected){hideSurfaces();$('sourceText').textContent='';stopRefresh();stopRealtime();showMode('画面已停止');showTouchMode('waiting');showH264Health('');}syncControlAvailability();return s;}
function deviceStateCopy(state){if(state==='device')return{label:'可连接',className:'ready'};if(state==='unauthorized')return{label:'等待 USB 授权',className:'unauthorized'};if(state==='offline')return{label:'ADB 离线',className:'offline'};return{label:'不可用',className:'error'};}
function renderDevices(data){devicesState=data||devicesState;const list=$('deviceList'),message=$('devicePanelMessage'),cancel=$('cancelConnect');$('autoConnect').checked=Boolean(devicesState.autoConnect);list.replaceChildren();cancel.hidden=!connectionBusy;if(connectionBusy){message.innerHTML='<span class="connecting-spinner"></span>正在建立手机控制会话，请保持手机解锁并确认必要的 USB 提示。';}
 else if(!devicesState.devices?.length)message.textContent='尚未发现 Android 手机。可以先打开助手，之后再插入手机；连接数据线并开启 USB 调试即可。';
 else if(devicesState.devices.length>1)message.textContent=`已发现 ${devicesState.devices.length} 台设备，请明确选择要控制的手机。`;else message.textContent='已发现 Android 手机。确认状态正常后，手动点击“连接”。';
 if(!devicesState.devices?.length){const empty=document.createElement('div');empty.className='device-empty';empty.textContent='未发现设备 · 插入手机后会自动刷新，也可以点“刷新设备”。';list.append(empty);return;}
 for(const device of devicesState.devices){const row=document.createElement('div');row.className='device-row'+(device.remembered?' remembered':'');const info=document.createElement('div'),title=document.createElement('div'),name=document.createElement('span'),state=document.createElement('span'),meta=document.createElement('div'),button=document.createElement('button');title.className='device-title-line';name.className='device-title';name.textContent=device.model||'Android 设备';const copy=deviceStateCopy(device.state);state.className='device-state tech '+copy.className;state.textContent=copy.label;title.append(name,state);if(device.remembered){const badge=document.createElement('span');badge.className='device-badge tech';badge.textContent='上次使用';title.append(badge);}meta.className='device-meta';meta.textContent=[device.os?`Android ${device.os}`:'Android',device.sdk?`API ${device.sdk}`:'',device.brand||''].filter(Boolean).join(' · ');info.append(title,meta);button.textContent=connectionBusy&&connectingRef===device.ref?'连接中…':'连接';button.className=device.state==='device'?'primary':'';button.disabled=connectionBusy||aiControlActive||device.state!=='device';button.onclick=()=>connectDevice(device.ref,device.model||'Android 手机');row.append(info,button);list.append(row);}}
async function refreshDevices({allowAuto=true,silent=false}={}){if(connected||connectionBusy||deviceRefreshPromise)return deviceRefreshPromise;deviceRefreshPromise=(async()=>{try{const data=await api('devices',undefined,{timeout:8000});renderDevices(data);if(allowAuto&&!autoConnectSuppressed&&data.autoConnect&&data.rememberedRef&&!autoConnectAttemptedRef){const remembered=data.devices?.find(item=>item.ref===data.rememberedRef&&item.state==='device');if(remembered){autoConnectAttemptedRef=remembered.ref;setTimeout(()=>{if(!connected&&!connectionBusy)$('deviceList')&&connectDevice(remembered.ref,remembered.model||'上次设备',true);},250);}}return data;}catch(e){if(!silent){$('devicePanelMessage').textContent='设备发现暂时失败：'+e.message;status(e.message,true);}return null;}finally{deviceRefreshPromise=null;}})();return deviceRefreshPromise;}
function stopDevicePolling(){if(devicePollTimer){clearTimeout(devicePollTimer);devicePollTimer=null;}}
function scheduleDevicePolling(delay=2200){stopDevicePolling();if(connected||connectionBusy||document.hidden)return;devicePollTimer=setTimeout(async()=>{devicePollTimer=null;await refreshDevices({allowAuto:true,silent:true});scheduleDevicePolling(2400);},delay);}
async function connectDevice(ref,label='Android 手机',automatic=false){if(connectionBusy||connected||aiControlActive)return;autoConnectSuppressed=false;connectionBusy=true;connectingRef=ref;connectCancelled=false;stopDevicePolling();renderDevices(devicesState);syncControlAvailability();$('connection').textContent='连接中';$('dot').classList.add('connecting');status((automatic?'正在自动连接上次设备：':'正在连接：')+label+'…');try{const result=await api('connect',{deviceRef:ref},{timeout:260000});if(connectCancelled)return;await updateState();status('已连接：'+(result.device?.model||label));await ensurePictureMode();}catch(e){if(!connectCancelled){status(e.message,true);$('dot').classList.add('error');await updateState().catch(()=>{});}}finally{connectionBusy=false;connectingRef=null;$('dot').classList.remove('connecting');renderDevices(devicesState);syncControlAvailability();if(!connected){await refreshDevices({allowAuto:false,silent:true});scheduleDevicePolling(1800);}}}
async function cancelConnection(){if(!connectionBusy)return;autoConnectSuppressed=true;connectCancelled=true;status('正在取消连接…');try{await api('cancel-connect',{}, {timeout:15000});}catch{}connectionBusy=false;connectingRef=null;await updateState().catch(()=>{});await refreshDevices({allowAuto:false,silent:true});scheduleDevicePolling(1200);status('已取消连接。');}
function realtimeInProgress(){return Boolean(streamController&&!streamController.signal.aborted);}
function cancelPreview(){if(previewController&&!previewController.signal.aborted)previewController.abort();previewController=null;}
async function frame(force=false){
 if((streamRunning||realtimeInProgress())&&!force)return false;
 if((!force&&!shouldRefresh({connected,automatic:$('automatic').checked,hidden:document.hidden}))||!connected||document.hidden||previewPromise)return false;
 const controller=new AbortController();previewController=controller;
 previewPromise=(async()=>{const timeoutTimer=setTimeout(()=>controller.abort('timeout'),12000);let response;try{response=await fetch('/api/screenshot',{headers:{'X-AndroidLink-Token':token},signal:controller.signal});}finally{clearTimeout(timeoutTimer);}if(response.status===409||response.status===429)return false;if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'画面刷新失败');}const blob=await response.blob();if(controller.signal.aborted)return false;const url=URL.createObjectURL(blob);revokeFallback();currentObjectURL=url;$('screen').src=url;showFallback();const captured=response.headers.get('X-AndroidLink-Captured-At');$('updated').textContent=captured?new Date(captured).toLocaleTimeString():new Date().toLocaleTimeString();return true;})();
 try{return await previewPromise;}catch(e){if(e.name==='AbortError'||e.name==='TimeoutError')return false;status(e.message,true);await updateState().catch(()=>{});return false;}finally{if(previewController===controller)previewController=null;previewPromise=null;}
}
function stopRefresh(){if(refreshTimer){clearTimeout(refreshTimer);refreshTimer=null;}cancelPreview();}
function scheduleRefresh(delay){if(streamRunning||realtimeInProgress())return;if(refreshTimer){clearTimeout(refreshTimer);refreshTimer=null;}if(!shouldRefresh({connected,automatic:$('automatic').checked,hidden:document.hidden}))return;const wait=delay??adaptiveRefreshDelay(lastActionAt);refreshTimer=setTimeout(async()=>{refreshTimer=null;await frame();if(connected&&Date.now()-lastStatusAt>=STATUS_CHECK_MS)await updateState().catch(()=>{});scheduleRefresh();},wait);}
function actionOccurred(){lastActionAt=Date.now();if(streamRunning||realtimeInProgress())return;cancelPreview();scheduleRefresh(POST_ACTION_REFRESH_MS);}
function clearH264RetryTimer(){if(h264RetryTimer){clearTimeout(h264RetryTimer);h264RetryTimer=null;}}
function stopH264Probe(){clearH264RetryTimer();if(probeController&&!probeController.signal.aborted)probeController.abort('probe-stopped');probeController=null;}
function stopRealtime(){streamAttempt++;stopH264Probe();stopTouchHealthPolling();if(streamController&&!streamController.signal.aborted)streamController.abort();streamController=null;streamRunning=false;activeStreamMode='';directTouchAvailable=false;gestureDirectTouch=false;pendingTouchMove=null;touchMovePump=false;showTouchMode('waiting');}
function rememberH264Failure(error,prefix='H.264 上次失败'){
 const info=classifyH264Failure(error);lastH264Failure=info;showH264Health(`${prefix}：${info.label}`,'warn',info.detail);return info;
}
function canRecoverH264(){return Boolean(connected&&!document.hidden&&$('automatic').checked&&realtimeAvailable&&streamRunning&&activeStreamMode==='mjpeg');}
function scheduleH264Recovery(delay){
 clearH264RetryTimer();if(!canRecoverH264())return;
 const wait=delay??nextH264RetryDelay(h264RetryFailures),label=lastH264Failure?.label||'本次启动未成功';
 showH264Health(`H.264 上次失败：${label} · ${retryDelayLabel(wait)}后后台重试`,'warn',lastH264Failure?.detail||'');
 h264RetryTimer=setTimeout(()=>{h264RetryTimer=null;attemptH264Recovery();},wait);
}
async function waitForInteractionIdle(signal,maxMs=15000){
 const started=Date.now();while(!signal.aborted&&(startPoint||exclusiveBusy)){if(Date.now()-started>=maxMs)return false;await new Promise(resolve=>setTimeout(resolve,180));}return !signal.aborted;
}
function handlePromotedH264Failure(controller,error){
 if(controller.signal.aborted||streamController!==controller)return;
 rememberH264Failure(error,'H.264 运行中断');h264RetryFailures=Math.min(h264RetryFailures+1,20);streamRunning=false;activeStreamMode='';directTouchAvailable=false;streamController=null;
 showMode('H.264 中断 · 正在恢复 MJPEG','starting');status('H.264 中断，正在恢复当前可用的 MJPEG 画面');startRealtime({skipH264:true});
}
function attemptH264Recovery(){
 if(!canRecoverH264()||probeController)return;
 if(startPoint||exclusiveBusy){scheduleH264Recovery(30000);return;}
 const attempt=streamAttempt,controller=new AbortController();probeController=controller;let promoted=false,promotionStarted=false;
 showH264Health('H.264 后台探测中 · 当前 MJPEG 画面不受影响','probing',lastH264Failure?.detail||'');
 const promote=async event=>{
  if(promotionStarted||controller.signal.aborted||attempt!==streamAttempt)return;promotionStarted=true;
  try{
   const idle=await waitForInteractionIdle(controller.signal);if(!idle)throw new Error('当前仍在操作手机，本次 H.264 自动切换已延后。');
   if(!canRecoverH264()||attempt!==streamAttempt)throw new Error('当前画面模式已变化，本次 H.264 后台探测已取消。');
   const previous=streamController;if(previous&&!previous.signal.aborted)previous.abort('promoting-to-h264');streamRunning=false;activeStreamMode='';directTouchAvailable=false;
   const result=await api('promote-stream',{streamId:event.streamId},{timeout:7000});if(controller.signal.aborted||attempt!==streamAttempt)return;
   promoted=true;streamController=controller;probeController=null;streamRunning=true;activeStreamMode='h264';directTouchAvailable=Boolean(result.directTouch);showTouchMode(directTouchAvailable?'scrcpy-video':'appium');scheduleTouchHealthPolling();targetFps=Number(result.targetFps)||event.targetFps||targetFps;h264RetryFailures=0;lastH264Failure=null;clearH264RetryTimer();
   showVideo('videoProbe');$('updated').textContent='实时';showMode(`H.264 实时流 · 目标 ${targetFps} fps${directTouchAvailable?' · 跟手触控':''}`,'live');showH264Health('H.264 已在后台恢复并自动切回','ok');status(directTouchAvailable?'已自动恢复 H.264 · 1:1 跟手触控可用':'已自动恢复 H.264 实时画面');
  }catch(error){if(controller.signal.aborted)return;rememberH264Failure(error,'H.264 后台恢复失败');h264RetryFailures=Math.min(h264RetryFailures+1,20);controller.abort('promotion-failed');probeController=null;showMode('H.264 恢复失败 · 正在恢复 MJPEG','starting');startRealtime({skipH264:true});}
 };
 const onState=event=>{if(controller.signal.aborted||attempt!==streamAttempt)return;reportVideoSize(event);if(event.state==='playing')promote(event);else if(event.state==='decoder-error')showH264Health('H.264 后台探测：浏览器解码异常','warn',event.error||'');};
 const onStats=stats=>{if(!promoted||streamController!==controller||controller.signal.aborted)return;reportStreamFeedback(stats);const fps=Math.round(stats.fps);$('updated').textContent=`${fps} fps`;$('streamMode').textContent=`H.264 实时流 · ${fps} fps / 目标 ${stats.targetFps}${directTouchAvailable?' · 1:1 跟手':''}`;};
 playRealtimeStream({token,canvas:$('videoProbe'),targetFps,signal:controller.signal,probe:true,onState,onStats}).then(()=>{if(promoted&&!controller.signal.aborted)handlePromotedH264Failure(controller,new Error('H.264 实时视频流已结束。'));}).catch(error=>{
  if(controller.signal.aborted||attempt!==streamAttempt)return;if(promoted){handlePromotedH264Failure(controller,error);return;}rememberH264Failure(error,'H.264 后台恢复失败');h264RetryFailures=Math.min(h264RetryFailures+1,20);probeController=null;scheduleH264Recovery();
 }).finally(()=>{if(probeController===controller)probeController=null;if(!promoted){$('videoProbe').style.display='none';}});
}
async function startRealtime({skipH264=false}={}){
 if(!connected||document.hidden||!$('automatic').checked||(!realtimeAvailable&&!mjpegAvailable))return false;
 const attempt=++streamAttempt;stopRefresh();stopH264Probe();if(streamController&&!streamController.signal.aborted)streamController.abort();const controller=new AbortController();streamController=controller;streamFallbackReason='';activeStreamMode='';
 try{displayHz=await measureDisplayHz(20);if(attempt!==streamAttempt||controller.signal.aborted)return false;targetFps=chooseTargetFps(displayHz,deviceRefreshHz);showMode(skipH264?'正在恢复 MJPEG 实时画面':`启动实时画面 · 目标 ${targetFps} fps`,'starting');}
 catch(e){displayHz=60;targetFps=chooseTargetFps(60,deviceRefreshHz);}
 const failures=[];
 const stateHandler=event=>{if(attempt!==streamAttempt||controller.signal.aborted)return;reportVideoSize(event);if(event.targetFps)targetFps=event.targetFps;if(event.state==='playing'){
  streamRunning=true;activeStreamMode=event.mode;directTouchAvailable=Boolean(event.directTouch);showTouchMode(directTouchAvailable?(event.mode==='h264'?'scrcpy-video':'scrcpy-control-only'):(event.mode==='mjpeg'?'connecting':'appium'));scheduleTouchHealthPolling();showVideo('video');$('updated').textContent='实时';const name=event.mode==='mjpeg'?'MJPEG 实时流':'H.264 实时流',touch=directTouchAvailable?' · 跟手触控':'';showMode(`${name} · 目标 ${targetFps} fps${touch}`,'live');
  if(event.mode==='mjpeg'){status(directTouchAvailable?'H.264 当前不可用，MJPEG 正常运行 · 已启用独立 1:1 跟手触控；后台会静默重试 H.264':'H.264 当前不可用，MJPEG 正常运行；后台会静默重试 H.264');scheduleH264Recovery();}else{h264RetryFailures=0;lastH264Failure=null;showH264Health('H.264 已连接','ok');status(directTouchAvailable?'H.264 实时画面已连接 · 拖动已启用 1:1 跟手':'H.264 实时画面已连接');}
 }else if(event.state==='decoder-error'){showMode('H.264 解码异常 · 尝试切换','error');}};
 const statsHandler=stats=>{if(attempt!==streamAttempt||streamController!==controller||!streamRunning)return;reportStreamFeedback(stats);const fps=Math.round(stats.fps),name=stats.mode==='mjpeg'?'MJPEG':'H.264',touch=directTouchAvailable?' · 1:1 跟手':'';$('updated').textContent=`${fps} fps`;$('streamMode').textContent=`${name} 实时流 · ${fps} fps / 目标 ${stats.targetFps}${touch}`;};
 (async()=>{
  if(realtimeAvailable&&!skipH264){
   try{await playRealtimeStream({token,canvas:$('video'),targetFps,signal:controller.signal,onState:stateHandler,onStats:statsHandler});if(controller.signal.aborted)return;failures.push('H.264：流已结束');}
   catch(e){if(controller.signal.aborted||attempt!==streamAttempt)return;failures.push('H.264：'+(e?.message||'启动失败'));rememberH264Failure(e);h264RetryFailures=0;streamRunning=false;activeStreamMode='';showMode('H.264 不可用 · 正在尝试 MJPEG','starting');status('H.264 未启动，正在自动尝试 MJPEG');}
  }
  if(controller.signal.aborted||attempt!==streamAttempt)return;
  if(mjpegAvailable){
   try{await playMjpegStream({token,canvas:$('video'),targetFps:Math.min(targetFps,60),signal:controller.signal,onState:stateHandler,onStats:statsHandler});if(controller.signal.aborted)return;failures.push('MJPEG：流已结束');}
   catch(e){if(controller.signal.aborted||attempt!==streamAttempt)return;failures.push('MJPEG：'+(e?.message||'启动失败'));streamRunning=false;activeStreamMode='';}
  }
  if(controller.signal.aborted||attempt!==streamAttempt)return;
  clearH264RetryTimer();stopTouchHealthPolling();streamFallbackReason=failures.join('；');if(streamController===controller)streamController=null;streamRunning=false;activeStreamMode='';directTouchAvailable=false;showTouchMode('appium');showMode('实时流不可用 · 已回退截图','fallback');status((streamFallbackReason||'实时流未启动')+'；已回退截图预览',true);scheduleRefresh(0);
 })().finally(()=>{if(streamController===controller&&(controller.signal.aborted||attempt!==streamAttempt))streamController=null;});
 return true;
}
async function ensurePictureMode(){if(!connected||document.hidden)return;if($('automatic').checked&&(realtimeAvailable||mjpegAvailable)){const ok=await startRealtime();if(ok)return;}streamRunning=false;scheduleRefresh(0);}
async function runControl(action,message){if(aiControlActive){status('AI 正在控制手机；如需操作，请先人工接管。',true);return;}const id=++latestOperation;lastActionAt=Date.now();if(!streamRunning)cancelPreview();if(refreshTimer){clearTimeout(refreshTimer);refreshTimer=null;}status(message+'…');try{const result=await action();if(id===latestOperation)status(result?.message||message+'完成');actionOccurred();return result;}catch(e){await updateState().catch(()=>{});if(id===latestOperation)status(e.message,true);if(!streamRunning)scheduleRefresh();}}
function setExclusiveBusy(value){exclusiveBusy=value;for(const id of ['save','openShots','reconnect','disconnect','source']){const el=$(id);if(el)el.disabled=value;}syncControlAvailability();}
async function runExclusive(action,message,{refresh=true,state=false,restartStream=false}={}){if(exclusiveBusy)return;setExclusiveBusy(true);if(restartStream)stopRealtime();if(!streamRunning)cancelPreview();if(refreshTimer){clearTimeout(refreshTimer);refreshTimer=null;}status(message+'…');try{const result=await action();if(state)await updateState();status(result?.message||message+'完成');if(restartStream&&connected)await ensurePictureMode();else if(refresh&&!streamRunning){lastActionAt=Date.now();scheduleRefresh(POST_ACTION_REFRESH_MS);}else if(!streamRunning)scheduleRefresh();return result;}catch(e){if(state)await updateState().catch(()=>{});status(e.message,true);if(restartStream&&connected)await ensurePictureMode();else if(!streamRunning)scheduleRefresh();}finally{setExclusiveBusy(false);}}
function showScreenshots(value){const section=$('captures'),list=$('shotList');if(!value?.items?.length){section.hidden=true;list.replaceChildren();return;}section.hidden=false;$('shotFolder').textContent='保存位置：'+value.directory;list.replaceChildren(...value.items.map(item=>{const li=document.createElement('li'),name=document.createElement('strong'),time=document.createElement('time');name.textContent=item.fileName;time.textContent=new Date(item.savedAt).toLocaleTimeString();li.append(name,time);return li;}));}
function recordingClock(seconds){const total=Math.max(0,Math.floor(Number(seconds)||0)),m=Math.floor(total/60),s=total%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function recordingSize(bytes){const value=Number(bytes)||0;if(value<1024)return value+' B';if(value<1024*1024)return (value/1024).toFixed(1)+' KB';return (value/1024/1024).toFixed(1)+' MB';}
function showRecordings(value){const section=$('recordings'),list=$('recordList'),items=value?.items||[];if(!items.length){section.hidden=true;list.replaceChildren();return;}section.hidden=false;$('recordFolder').textContent='保存位置：'+(value.directory||'Mac 本地录屏目录');list.replaceChildren(...items.map(item=>{const li=document.createElement('li'),name=document.createElement('strong'),time=document.createElement('time');name.textContent=item.fileName;time.textContent=`${new Date(item.savedAt).toLocaleTimeString()} · ${recordingClock((item.durationMs||0)/1000)} · ${recordingSize(item.sizeBytes)}`;li.append(name,time);return li;}));}
function stopRecordingTimers(){if(recordingUiTimer){clearInterval(recordingUiTimer);recordingUiTimer=null;}if(recordingPollTimer){clearTimeout(recordingPollTimer);recordingPollTimer=null;}}
function scheduleRecordingPoll(delay=1000){if(recordingPollTimer)clearTimeout(recordingPollTimer);const active=['recording','stopping','pending-pull'].includes(recordingState?.phase);if(!active||document.hidden)return;recordingPollTimer=setTimeout(async()=>{recordingPollTimer=null;try{applyRecordingState(await api('recording',undefined,{timeout:4000}));}catch{}scheduleRecordingPoll(1200);},delay);}
function applyRecordingState(value){if(!value)return;const previous=recordingState,button=$('record'),meta=$('recordMeta');recordingState={...recordingState,...value};showRecordings(recordingState);button.className='record-button';button.disabled=aiControlActive||recordingBusy||(!connected&&recordingState.phase==='idle');if(recordingState.phase==='recording'){button.classList.add('recording');button.textContent=`■ 停止录屏 · ${recordingClock(recordingState.elapsedSeconds)}`;meta.textContent=`手机正在原生录屏${recordingState.profile?.label?' · '+recordingState.profile.label:''} · 单段最长约 ${Math.ceil((recordingState.maxDurationSeconds||175)/60)} 分钟 · 停止后自动回传 Mac`;meta.className='record-meta recording';if(!recordingUiTimer)recordingUiTimer=setInterval(()=>{if(recordingState.phase!=='recording')return;recordingState.elapsedSeconds=(recordingState.elapsedSeconds||0)+1;button.textContent=`■ 停止录屏 · ${recordingClock(recordingState.elapsedSeconds)}`;},1000);scheduleRecordingPoll();}else if(recordingState.phase==='stopping'){button.classList.add('recording');button.disabled=true;button.textContent='■ 正在停止并回传…';meta.textContent='正在让手机结束录屏并把 MP4 回传到 Mac…';meta.className='record-meta recording';scheduleRecordingPoll();}else if(recordingState.phase==='pending-pull'){if(recordingUiTimer){clearInterval(recordingUiTimer);recordingUiTimer=null;}button.classList.add('pending');button.textContent='↻ 重试回传录屏';meta.textContent=recordingState.lastError||'手机录屏已停止，但尚未成功回传到 Mac。';meta.className='record-meta error';scheduleRecordingPoll();}else{if(recordingUiTimer){clearInterval(recordingUiTimer);recordingUiTimer=null;}if(recordingPollTimer){clearTimeout(recordingPollTimer);recordingPollTimer=null;}button.textContent='● 开始录屏';meta.textContent='手机端原生录屏 · 停止后自动回传 Mac';meta.className='record-meta';const newest=recordingState.items?.[0];if(newest?.fileName&&newest.fileName!==lastRecordingFile){if(previous?.phase&&previous.phase!=='idle')status('录屏已保存到 Mac：'+newest.fileName);lastRecordingFile=newest.fileName;}}}
async function toggleRecording(){if(recordingBusy)return;if(aiControlActive){status('AI 正在控制手机；请先人工接管再录屏。',true);return;}recordingBusy=true;applyRecordingState(recordingState);try{if(recordingState.phase==='recording'||recordingState.phase==='pending-pull'){status(recordingState.phase==='pending-pull'?'正在重试回传录屏…':'正在停止手机录屏并回传到 Mac…');const result=await api('stop-recording',{}, {timeout:210000});applyRecordingState(result.recording);showRecordings(result.recording);status('录屏已保存到 Mac：'+result.fileName);}else if(recordingState.phase==='idle'){status('正在启动手机原生录屏…');const result=await api('start-recording',{}, {timeout:12000});applyRecordingState(result.recording);status('手机录屏已开始'+(result.recording?.profile?.label?' · '+result.recording.profile.label:'')+' · 可继续正常操控');}}catch(e){status(e.message,true);try{applyRecordingState(await api('recording',undefined,{timeout:4000}));}catch{}}finally{recordingBusy=false;applyRecordingState(recordingState);}}

$('copyMcpJson').onclick=async()=>{try{if(!aiIntegrationState)await refreshAiIntegrations();await copyText(aiIntegrationState?.snippets?.json);aiIntegrationMessage('已复制 JSON MCP 配置');}catch(error){aiIntegrationMessage(error.message,true);}};
$('copyMcpToml').onclick=async()=>{try{if(!aiIntegrationState)await refreshAiIntegrations();await copyText(aiIntegrationState?.snippets?.toml);aiIntegrationMessage('已复制 TOML MCP 配置');}catch(error){aiIntegrationMessage(error.message,true);}};
$('copyMcpCommand').onclick=async()=>{try{if(!aiIntegrationState)await refreshAiIntegrations();await copyText(aiIntegrationState?.snippets?.command);aiIntegrationMessage('已复制 MCP 启动命令');}catch(error){aiIntegrationMessage(error.message,true);}};
$('testMcp').onclick=async()=>{const button=$('testMcp');button.disabled=true;aiIntegrationMessage('正在测试 MCP Server、工具注册和助手 IPC…');try{const result=await api('mcp-test',{}, {timeout:10000});aiIntegrationMessage(`MCP 正常 · ${result.toolCount} 个工具 · ${result.status?.connected?'手机已连接':'助手已连接，手机当前未连接'}`);}catch(error){aiIntegrationMessage(error.message,true);}finally{button.disabled=false;}};
$('takeover').onclick=async()=>{const button=$('takeover');button.disabled=true;try{const result=await api('takeover',{}, {timeout:5000});syncAiControl(result);status('已停止 AI 控制，人工操作已恢复');await updateState();}catch(e){status(e.message,true);}finally{button.disabled=false;}};
$('back').onclick=()=>runControl(()=>api('back',{}),'返回');
$('home').onclick=()=>runControl(()=>api('home',{}),'回到主屏');
$('recent').onclick=()=>runControl(()=>api('recent',{}),'打开最近任务');
$('notifications').onclick=()=>runControl(()=>api('notifications',{}),'打开通知栏');
$('quickSettings').onclick=()=>runControl(()=>api('quick-settings',{}),'打开快捷设置');
$('collapsePanel').onclick=()=>runControl(()=>api('collapse-panel',{}),'收起系统面板');
$('refresh').onclick=async()=>{if(streamRunning||realtimeAvailable||mjpegAvailable){stopRealtime();showMode('正在重启实时画面','starting');await ensurePictureMode();return;}cancelPreview();if(refreshTimer){clearTimeout(refreshTimer);refreshTimer=null;}status('刷新画面…');const ok=await frame(true);if(ok)status('画面已刷新');scheduleRefresh();};
$('save').onclick=()=>runExclusive(async()=>{const saved=await api('save-screenshot',{}, {timeout:35000}),all=await api('screenshots');showScreenshots(all);return{message:'已保存：'+saved.fileName};},'正在分析并保存原始 PNG',{refresh:false});
$('openShots').onclick=()=>runExclusive(()=>api('open-screenshot-folder',{}),'打开截图文件夹',{refresh:false});
$('record').onclick=toggleRecording;
$('openRecordings').onclick=async()=>{const button=$('openRecordings');button.disabled=true;try{await api('open-recording-folder',{}, {timeout:10000});status('已打开录屏文件夹');}catch(e){status(e.message,true);}finally{button.disabled=false;}};
const swipeCopy={up:['↑ 向上滑','↑ 正在上滑…','向上滑'],down:['↓ 向下滑','↓ 正在下滑…','向下滑'],left:['← 向左滑','← 正在左滑…','向左滑'],right:['向右滑 →','正在右滑… →','向右滑']};
document.querySelectorAll('[data-direction]').forEach(b=>b.onclick=async()=>{if(b.classList.contains('running'))return;const copy=swipeCopy[b.dataset.direction];b.classList.add('running');b.setAttribute('aria-busy','true');b.textContent=copy[1];try{await runControl(()=>api('swipe',{direction:b.dataset.direction}),copy[2]);}finally{b.classList.remove('running');b.removeAttribute('aria-busy');b.textContent=copy[0];}});
$('input').onclick=()=>runControl(async()=>{await api('input',{text:$('text').value});$('text').value='';},'输入文字');
$('reconnect').onclick=()=>runExclusive(()=>api('connect',{}, {timeout:260000}),'重新连接',{state:true,restartStream:true});
$('refreshDevices').onclick=async()=>{status('正在刷新设备列表…');await refreshDevices({allowAuto:false});if(!connected)status('设备列表已刷新。');};
$('cancelConnect').onclick=cancelConnection;
$('autoConnect').onchange=async()=>{const enabled=$('autoConnect').checked;devicesState.autoConnect=enabled;try{await api('ui-preference',{autoConnect:enabled},{timeout:3000});status(enabled?'已开启：以后自动连接上次设备':'已关闭自动连接；以后由你手动点击连接');if(enabled)refreshDevices({allowAuto:true,silent:true});}catch(e){$('autoConnect').checked=!enabled;devicesState.autoConnect=!enabled;status(e.message,true);}};
$('disconnect').onclick=async()=>{autoConnectSuppressed=true;await runExclusive(()=>api('disconnect',{}),'断开手机',{refresh:false,state:true,restartStream:true});if(!connected){await refreshDevices({allowAuto:false,silent:true});scheduleDevicePolling(800);}};
$('quit').onclick=async()=>{const button=$('quit');button.disabled=true;try{status('正在退出安卓连接助手…');await api('quit',{}, {timeout:3000});stopRefresh();stopRealtime();setTimeout(()=>{document.body.classList.add('quitting');status('安卓连接助手已退出，可以关闭此页面。');},350);}catch(e){status(e.message,true);button.disabled=false;}};
$('source').onclick=()=>runExclusive(async()=>{$('sourceText').textContent=(await api('source',undefined,{timeout:20000})).source;},'读取页面结构',{refresh:false});
$('advancedChecks').addEventListener('toggle',()=>{if($('advancedChecks').open)scheduleDiagnosticPolling(0);else stopDiagnosticPolling();});
$('exportDiagnostic').onclick=async()=>{const button=$('exportDiagnostic'),out=$('diagnosticExport');button.disabled=true;out.textContent='正在生成脱敏诊断…';out.classList.remove('error');try{const result=await api('export-diagnostic',{}, {timeout:20000});out.textContent='已导出到桌面：'+result.fileName;await refreshDiagnostics();}catch(error){out.textContent=error.message;out.classList.add('error');}finally{button.disabled=false;}};
function activeSurface(){if($('videoProbe').style.display!=='none'&&$('videoProbe').offsetWidth)return $('videoProbe');if($('video').style.display!=='none'&&$('video').offsetWidth)return $('video');return $('screen');}
function point(e){const surface=activeSurface(),r=surface.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
function pointerVisual(e,state='hover'){const dot=$('pointerIndicator');dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px';dot.className='pointer-indicator visible '+state;}
function hidePointerVisual(){if(!startPoint)$('pointerIndicator').className='pointer-indicator';}
function showDragOrigin(){if(!startClientPoint)return;const origin=$('dragOrigin');origin.style.left=startClientPoint.x+'px';origin.style.top=startClientPoint.y+'px';origin.className='drag-origin visible';}
function hideDragOrigin(){$('dragOrigin').className='drag-origin';}
function tapPulse(e){const pulse=$('tapPulse');pulse.style.left=e.clientX+'px';pulse.style.top=e.clientY+'px';pulse.className='tap-pulse';void pulse.offsetWidth;pulse.className='tap-pulse animate';}
function touchRequest(action,p){return api('touch',{action,x:p.x,y:p.y},{timeout:action==='move'?900:1800});}
function beginDirectTouch(p){directTouchFailed=false;pendingTouchMove=null;touchMovePump=false;touchChain=Promise.resolve().then(()=>touchRequest('down',p)).catch(error=>{directTouchFailed=true;directTouchAvailable=false;gestureDirectTouch=false;showTouchMode('appium',error?.message||'');scheduleTouchHealthPolling(300);throw error;});}
function queueDirectMove(p){pendingTouchMove=p;if(touchMovePump||!gestureDirectTouch||!directTouchAvailable)return;touchMovePump=true;touchChain=touchChain.catch(()=>{}).then(async()=>{try{while(pendingTouchMove&&gestureDirectTouch&&directTouchAvailable){const latest=pendingTouchMove;pendingTouchMove=null;await touchRequest('move',latest);}}catch(error){directTouchFailed=true;directTouchAvailable=false;gestureDirectTouch=false;pendingTouchMove=null;showTouchMode('appium',error?.message||'');scheduleTouchHealthPolling(300);throw error;}finally{touchMovePump=false;}});}
async function finishDirectTouch(p,holdMs=45){pendingTouchMove=p;queueDirectMove(p);try{await touchChain;}catch{}if(directTouchFailed||!directTouchAvailable)return false;if(holdMs>0)await new Promise(resolve=>setTimeout(resolve,holdMs));try{touchChain=touchChain.catch(()=>{}).then(()=>touchRequest('up',p));await touchChain;return true;}catch(error){directTouchFailed=true;directTouchAvailable=false;showTouchMode('appium',error?.message||'');scheduleTouchHealthPolling(300);return false;}}
function pointerDown(e){if(!connected||e.button!==0)return;if(aiControlActive){status('AI 正在控制手机；如需人工操作，请先点“停止 AI 并接管”。',true);return;}startPoint=point(e);startClientPoint={x:e.clientX,y:e.clientY};pointerDownAt=performance.now();pointerDragging=false;gestureDirectTouch=directTouchAvailable;pointerVisual(e,'pressed');hideDragOrigin();e.currentTarget.setPointerCapture(e.pointerId);if(gestureDirectTouch)beginDirectTouch(startPoint);status(gestureDirectTouch?'按住拖动 · 手机正在实时跟随鼠标':'按住拖动 · 当前为兼容模式，松手后执行');}
function pointerMove(e){pointerVisual(e,startPoint?(pointerDragging?'dragging':'pressed'):'hover');if(!startPoint||!connected)return;const travel=Math.hypot(e.clientX-startClientPoint.x,e.clientY-startClientPoint.y);if(travel>=7&&!pointerDragging){pointerDragging=true;showDragOrigin();status(gestureDirectTouch?'拖动中 · 手机边拖边动 · 1:1 距离映射':'拖动中 · 兼容模式，松手后按 1:1 距离执行');}if(pointerDragging&&gestureDirectTouch)queueDirectMove(point(e));}
async function pointerUp(e){if(!startPoint||!connected)return;const from=startPoint,to=point(e),durationMs=Math.max(0,performance.now()-pointerDownAt),tap=!pointerDragging&&Math.hypot(e.clientX-startClientPoint.x,e.clientY-startClientPoint.y)<7,wasDirect=gestureDirectTouch;startPoint=null;startClientPoint=null;pointerDragging=false;hideDragOrigin();pointerVisual(e,'hover');if(tap)tapPulse(e);if(wasDirect){const ok=await finishDirectTouch(to,tap?20:45);gestureDirectTouch=false;lastActionAt=Date.now();if(ok){status(tap?'轻点完成':'拖动完成 · 全程实时跟手');return;}}gestureDirectTouch=false;
 runControl(()=>api(tap?'tap':'drag',tap?to:{from,to,durationMs}),tap?'轻点':'精准拖动');}
async function pointerCancel(e){const p=startPoint?point(e):null;const hadDirect=Boolean(startPoint&&gestureDirectTouch);startPoint=null;startClientPoint=null;pointerDragging=false;gestureDirectTouch=false;hideDragOrigin();hidePointerVisual();if(hadDirect&&p){try{await touchRequest('cancel',p);}catch{}}}
for(const surface of [$('screen'),$('video'),$('videoProbe')]){surface.onpointerenter=e=>pointerVisual(e,'hover');surface.onpointermove=pointerMove;surface.onpointerleave=()=>hidePointerVisual();surface.onpointerdown=pointerDown;surface.onpointercancel=pointerCancel;surface.onpointerup=pointerUp;}
document.querySelectorAll('[data-preview-size]').forEach(button=>button.onclick=async()=>{const size=applyPreviewSize(button.dataset.previewSize);status(`显示尺寸：${PREVIEW_SIZE_LABELS[size]} · ${PREVIEW_SIZES[size]} px`);try{await api('ui-preference',{previewSize:size},{timeout:3000});}catch{status(`显示尺寸已切换为${PREVIEW_SIZE_LABELS[size]}，但本次未能保存偏好。`,true);}});
$('automatic').onchange=async()=>{stopRefresh();stopRealtime();if($('automatic').checked){await ensurePictureMode();}else{showMode('自动画面已关闭');showTouchMode('waiting');showH264Health('');status('自动画面已关闭，可点“刷新画面”获取静态截图');}};
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopRefresh();stopRealtime();stopDevicePolling();stopDiagnosticPolling();if(recordingPollTimer){clearTimeout(recordingPollTimer);recordingPollTimer=null;}}else{updateState().catch(()=>{}).finally(()=>{if(connected)ensurePictureMode();else{refreshDevices({allowAuto:true,silent:true});scheduleDevicePolling(500);}scheduleRecordingPoll(300);if($('advancedChecks')?.open)scheduleDiagnosticPolling(0);if(aiIntegrationState)refreshAiIntegrations();});}});
window.addEventListener('beforeunload',()=>{stopRefresh();stopRealtime();stopDevicePolling();stopDiagnosticPolling();revokeFallback();});

(async()=>{try{await updateState();showScreenshots(await api('screenshots'));applyRecordingState(await api('recording'));await refreshAiIntegrations();if(connected){status('手机已连接');await ensurePictureMode();}else{status('助手已就绪，选择设备后点击连接。');await refreshDevices({allowAuto:true});scheduleDevicePolling();}}catch(e){status(e.message,true);scheduleDevicePolling(1200);}})();
